model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  contact:
    cutoff: 8.0
    deterministic: true
  contact_enabled: true
  latent_enabled: false

data:
  data_module:
    data_loaders:
      num_workers: 10

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 40000
  decay_every_n_steps: 5000