name: protseed
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - pip:
      - biopython==1.79
      - deepspeed==0.9.4
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.2
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==4.6.3
      - pytorch_lightning==1.5.10
      - wandb==0.12.21
      - beautifulsoup4
      - pandas
      # - git+ssh://git@github.com/NVIDIA/dllogger.git
      # - git+https://github.com/NVIDIA/dllogger.git
      - -f https://data.pyg.org/whl/torch-1.12.0+cu113.html
      - torch_cluster==1.6.0+pt112cu113
      - torch_scatter==2.1.0+pt112cu113
      - torch_sparse==0.6.16+pt112cu113
      - torch_spline_conv==1.2.1+pt112cu113
      - pyg_lib==0.2.0+pt112cu113
      - torch-geometric==2.3.1
  - intel-openmp=2021.4.0
  - pytorch::pytorch=1.12.*
  - conda-forge::python=3.9
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - conda-forge::cudatoolkit=11.3.*
  - conda-forge::ipython
  - conda-forge::scikit-learn
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - bioconda::aria2
